os: linux
dist: focal

services:
    - docker

env:
    - ProjectsDir=build/xyteam
      
before_install:
    - docker pull xyteam/autobdd-run:2.1.0
    
script:
    - |
        cd .docker
        docker-compose run --rm calculator-app-run "make test" 