os: linux
dist: focal
language: node_js

services:
    - docker

before_install:
    - docker pull xyteam/autobdd-run:2.1.0
    
script:
    - |
        cd .docker && source .env && docker-compose run --rm calculator-app-run "make test" 