os: linux
dist: focal

services:
    - docker

env:
    - ProjectsBase=build/xyteam
      
before_install:
    - docker pull xyteam/autobdd-run:2.1.0
    
script:
    - |
        cd .docker
        docker-compose run --rm calculator-app-run "make js-test" 
        docker-compose run --rm calculator-app-run "make py-test"
        docker-compose run --rm calculator-app-run "make int-test"
        docker-compose run --rm calculator-app-run "make e2e-test"  