os: linux
dist: focal
language: node_js

services:
    - docker
  
before_install:
    - cd .docker
    - docker-compose pull calculator-app-run

script:
    - |
        cd .docker
        docker-compose run --rm calculator-app-run "make test" 