jobs:
  build:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"    
    steps:
      - checkout
      - run: make js-test
      - run: make py-test
      - run: make int-test
      - run: make e2e-test
    store_test_results:
      path: test-results

orbs:
  node: circleci/node@3.0.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
