version: 2.0
orbs:
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    docker_layer_caching: true
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  unit-test:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    docker_layer_caching: true
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: js unit test
          command: make js-test
      - store_test_results:
          path: test-results/js-code/
      - store_artifacts:
          path: test-results/js-code
      - persist_to_workspace:
          root: ./
          paths:
            - .test-results/js-code
      - run:
          name: py unit test
          command: make py-test
      - store_test_results:
          path: test-results/py-code
      - store_artifacts:
          path: test-results/py-code
      - persist_to_workspace:
            root: ./
            paths:
              - .test-results/py-code
  int-test:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    docker_layer_caching: true
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: int test
          command: make int-test
      - store_test_results:
          path: test-results/cal-app
      - store_artifacts:
          path: test-results/cal-app  
      - persist_to_workspace:
          root: ./
          paths:
            - .test-results/cal-app
  e2e-test:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    docker_layer_caching: true
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: e2e test
          command: make e2e-test
      - store_test_results:
          path: test-results/e2e-test
      - store_artifacts:
          path: test-results/e2e-test
      - persist_to_workspace:
          root: ./
          paths:
            - .test-results/e2e-test
  allure-report:  
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    docker_layer_caching: true
    working_directory: ~/Projects/AutoBDD/test-projects/test-calculator
    environment:
      BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - attach_workspace:
          at: ./test-results/js-code
          at: ./test-results/py-code
          at: ./test-results/cal-app
          at: ./test-results/e2e-test
      - run:
          name: generate unit-test report
          command: |
            allure generate \
              --config .allure/allure.yml \
              --report-dir test-results/unit-test-report \
              test-results/js-code test-results/py-code test-results/cal-app
      - run:
          name: generate e2e-test report
          command: |
            allure generate \
              --config .allure/allure.yml \
              --report-dir test-results/e2e-test-report \
              test-results/e2e-test
      - run:
          name: tgz test-results
          command: |
            tar cf - ./test-results > gzip > test-results.tgz
      - store_artifacts:
          path: test-results.tgz
          destination: test-results.tgz

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build    
      - int-test:
          requires:
            - build    
      - e2e-test:
          requires:
            - build
      - allure-report:
          requires:
            - unit-test
            - int-test
            - e2e-test